name: Vagrant Development Build
on:
  push:
  workflow_dispatch:

jobs:
  trigger-build:
    name: Trigger Vagrant Development Build
    runs-on: ubuntu-latest
    container:
      # however, it seems to take forever to download ruby
      # whereas actions/setup-go has some go caching built in
      # image: public.ecr.aws/docker/library/golang:1.20
      image: public.ecr.aws/docker/library/ruby:3.1.2
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3.6.0
        with:
          submodules: true
      - name: setup golang
        uses: actions/setup-go@v4
        with:
          # this version comes from the go.mod file
          go-version: '1.20'
      - name: Development Build
        shell: bash
        run: |
          set -eu
          if [ -n "${BASH_VERSION:-}" ]; then
              set -o pipefail
          fi
          if ! command -v ruby &>/dev/null; then
            apt-get update
            apt-get install -y curl jq rbenv vim-tiny
            eval "$(rbenv init -)"
            rbenv install -s $(cat .ruby-version)
            PATH=/usr/local/go/bin:$HOME/go/bin:$PATH
          fi
          echo '# <go env>'
          go env
          echo '# </go env>'
          make bin/linux
          gem build vagrant.gemspec
          gem install ./vagrant*gem
          ./bin/vagrant --version
          ./bin/vagrant version
          ./bin/vagrant help || true
        env:
          DEBIAN_FRONTEND: noninteractive
