on:
  push:
    tags: 'v*'

jobs:
  trigger-release:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Installers Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Trigger Build
        run: ./.ci/release
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
